version: '2.0'
services:
  app:
    build:
      context: ./backend
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app
      - ./DatiCsv:/app/DatiCsv
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    networks:
      - mynetwork
    depends_on:
      - app
  
  load_balancer:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - frontend
    ports:
      - "80:80"
    networks:
      - mynetwork

networks:
  mynetwork: