version: '1.2'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
      - ./DatiCsv:/app/backend/DatiCsv
    networks:
      - mynetwork

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    networks:
      - mynetwork
    depends_on:
      - backend
  
  load_balancer:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    ports:
      - "8080:80"

networks:
  mynetwork:
